"""empty message

Revision ID: ad83c3873756
Revises: 0a9673b6f14a
Create Date: 2019-03-11 19:11:57.157719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad83c3873756'
down_revision = '0a9673b6f14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('approver', sa.String(length=128), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['license.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_component_conn',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=128), nullable=True),
    sa.Column('modification', sa.Boolean(), nullable=True),
    sa.Column('delivery', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'component_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_component_conn')
    op.drop_table('product')
    # ### end Alembic commands ###
